import type { CatInfo } from '@/types'

export const CATS: CatInfo[] = [
  {
    id: 'CAT01', name: 'Signup', tag: 'signup',
    description: 'New user registration (WIP)', active: false,
    scenarios: [],
  },
  {
    id: 'CAT02', name: 'Onboarding', tag: 'onboarding',
    description: 'User onboarding flow (WIP)', active: false,
    scenarios: [],
  },
  {
    id: 'CAT03', name: 'Login', tag: 'login',
    description: 'User authentication flows', active: true,
    scenarios: [
      'LN001 - Next page loads within 5 seconds after successful login',
      'LN002 - Login button is disabled when all fields are empty',
      'LN003 - Successful login with valid credentials',
      'LN004 - Login with invalid email format shows email field error',
      'LN005 - Toggle login password visibility',
      'LN006 - Navigate to sign up page',
      'LN007 - Forgot password link opens reset modal',
      'LN008 - Valid email in reset form sends password reset link',
      'LN009 - Password reset modal can be closed',
      'LN010 - Login with Google redirects to the dashboard',
    ],
  },
  {
    id: 'CAT04', name: 'Avatar Management', tag: 'avatar-management',
    description: 'Create and manage avatars', active: true,
    scenarios: [
      'AVM001 - Avatar switcher menu opens with Switch Avatars and Create New Avatar sections',
      'AVM002 - Both "Create New Avatar" entry points navigate to /new',
      'AVM003 - Completing new avatar creation redirects to the dashboard with the new avatar selected',
      'AVM004 - With multiple avatars: current is tagged and disabled; others are enabled; clicking one switches the dashboard',
      'AVM005 - Delete button is enabled when multiple avatars exist',
      'AVM009 - Delete button is disabled when only one avatar exists',
    ],
  },
  {
    id: 'CAT05', name: 'Home', tag: 'home',
    description: 'Home page features', active: true,
    scenarios: [
      'HM001 - Greeting section is visible',
      'HM002 - Greeting text matches the current time of day',
      'HM003 - "Add Video AI to your profile" card redirects to /video-ai',
      'HM004 - "Enrich your Knowledge Base" card redirects to /knowledge-base',
      'HM005 - "Add bio to your profile" card redirects to /profile-builder',
      'HM006 - "Clone your voice" card opens voice clone modal in knowledge base',
      'HM007 - Avatar Metrics chart loads with data',
    ],
  },
  {
    id: 'CAT06', name: 'Knowledge Base', tag: 'knowledge-base',
    description: 'KB creation and management', active: false,
    scenarios: [
      'KB001 - All integration buttons are visible in main toolbar and expanded menu',
      'KB002 - Every integration button opens the modal and shows a pending card',
      'KB003 - All three modal close methods dismiss the modal and remove the pending card',
      'KB004 - Invalid URL shows validation error for all platforms',
      'KB005 - URL from wrong platform shows validation error for all platforms',
      'KB006 - All platform integrations complete successfully',
      'KB007 - Loaded card shows profile name, image and correct post count',
      'KB008 - Config modal Profile tab shows bio and account information for all integrations',
      'KB009 - Config modal Posts tab lists minimum posts with title, date and action menus',
      'KB010 - Post "More details" shows full metadata',
      'KB011 - Config modal Metadata tab shows integration details',
      'KB012 - Load Latest Posts triggers integration refresh',
      'KB013 - Social integrations can be deleted via config modal or card button',
      'KB014 - Adding an already-connected URL shows duplicate error',
      'KB015 - Bulk drag-select deletes all selected integrations',
      'KB016 - Creating other source integrations shows the cards in the canvas',
      'KB017 - Text and Biography sources are editable from the config modal',
      'KB018 - Disabling a source sets isEnabled to false',
      'KB019 - Enabling a source sets isEnabled to true',
      'KB020 - Conversations skill shows always-active status',
      'KB021 - Seller skill toggle enables and disables sell products action',
      'KB022 - Uploading an audio file creates a voice clone and shows Voice Calls node',
      'KB023 - Voice call buttons disappear and reappear in classic EU when skill is toggled',
      'KB024 - Voice call buttons disappear and reappear in modern EU when skill is toggled',
      'KB025 - Canvas mode buttons, zoom controls and fullscreen all work correctly',
    ],
  },
  {
    id: 'CAT07', name: 'EU Authentication', tag: 'end-user-auth',
    description: 'End-user auth flows', active: true,
    scenarios: [
      'EU001 - Auth modal opens from multiple entry points with all login options',
      'EU002 - Complete email signup with display name creates a new account',
      'EU003 - Password visibility toggles work on both password fields',
      'EU004 - Signing in with valid email credentials logs the user in',
      'EU005 - Login with Google logs into the end user',
      'EU006 - Login with X via Google logs into the end user',
      'EU007 - Login with Facebook logs into the end user',
      'EU011 - Log out via the profile menu ends the user session',
      'EU012 - Editing Display Name and Bio in the profile form persists changes',
      'EU013 - Bio field enforces the 150 character limit',
      'EU014 - Share Profile button copies the user profile URL to clipboard',
      'EU015 - Create AI Avatar link carries the correct UTM tracking parameters',
      'EU016 - Change Password form is accessible from the Settings tab',
      'EU001M - Auth modal opens from multiple entry points with all login options (Modern)',
      'EU002M - Complete email signup with display name creates a new account (Modern)',
      'EU003M - Password visibility toggles work on both password fields (Modern)',
      'EU004M - Signing in with valid email credentials logs the user in (Modern)',
      'EU011M - Log out via the profile menu ends the user session (Modern)',
      'EU012M - Editing Display Name and Bio in Modern EU persists changes',
      'EU013M - Bio field enforces the 150 character limit in Modern EU',
      'EU016M - Change Password form is accessible from the Settings tab in Modern EU',
    ],
  },
  {
    id: 'CAT08', name: 'End User', tag: 'end-user',
    description: 'End-user experience', active: true,
    scenarios: [
      'EU008 - Opening the chat fires the required API requests and shows the Avatar\'s welcome message',
      'EU009 - Sending a message receives a response from the Avatar',
      'EU010 - Voice call starts automatically after login and fires a call request',
      'EU008M - Opening the Modern EU chat fires the required API requests and shows the Avatar\'s welcome message',
      'EU009M - Sending a message on the Modern EU receives a response from the Avatar',
      'EU010M - Modern EU voice call starts automatically after login and fires a call request',
    ],
  },
  {
    id: 'CAT09', name: 'Chat Log', tag: 'chat-log',
    description: 'Chat history and logs', active: true,
    scenarios: [
      'CL001 - Chat log page loads with all required UI elements visible',
      'CL002 - Clicking a conversation opens the message thread in the details panel',
      'CL003 - Searching for a term with no results shows the no-matching-results message',
      'CL004 - Selecting a date range and clicking Apply filters the conversation list',
      'CL005 - Clicking Clear filter resets the date range to the default',
      'CL006 - Clicking the refresh button reloads the conversation list',
      'CL007 - A message sent from the end user as an anonymous user appears in the chat log',
      'CL008 - A multi-turn dialogue from the end user appears with correct content in the chat log',
      'CL009 - A message sent by a logged-in user shows their display name in the chat log',
      'CL010 - An anonymous user who signs up after messaging has their name updated in the chat log',
      'CL011 - Opening the chat without sending a message does not create a chat log entry',
      'CL007M - A message sent from the Modern end user as an anonymous user appears in the chat log',
      'CL008M - A multi-turn dialogue from the Modern end user appears with correct content in the chat log',
      'CL009M - A message sent by a logged-in Modern EU user shows their display name in the chat log',
      'CL010M - An anonymous Modern EU user who signs up after messaging has their name updated in the chat log',
      'CL011M - Opening the Modern EU chat without sending a message does not create a chat log entry',
    ],
  },
  {
    id: 'CAT10', name: 'Video AI', tag: 'video-ai',
    description: 'Video AI generation', active: true,
    scenarios: [
      'VAI001 - Talk to the camera shows full form UI, accepts 1 avatar image and has 2 audio options',
      'VAI002 - Create scene shows full form UI, accepts up to 5 reference images and has 3 audio options',
      'VAI003 - Product placement shows full form UI, accepts avatar and product images and has 2 audio options',
      'VAI004 - All audio input methods can be saved without errors',
      'VAI005 - All video styles, behaviors and creativity slider can be configured',
      'VAI006 - Talk to the camera generates a video with a script',
      'VAI007 - Talk to the camera generates a video without a script',
      'VAI008 - Create scene generates a video',
      'VAI009 - Product placement generates a video with avatar and product images',
      'VAI010 - Create scene generates a video with audio disabled',
      'VAI011 - Video player controls work correctly',
      'VAI012 - A generated video can be added and removed from the user profile (Classic)',
      'VAI013 - A generated video can be added and removed from the user profile (Modern)',
      'VAI014 - A completed video can be regenerated',
      'VAI015 - Deleting a scene calls the delete API and removes the video player',
    ],
  },
  {
    id: 'CAT11', name: 'Profile Builder (General)', tag: 'profile-builder-general',
    description: 'General profile settings', active: true,
    scenarios: [
      'PBG001 - All General form sections are visible',
      'PBG002 - Save and Cancel are disabled initially and become enabled after editing',
      'PBG003 - Clearing the title field shows the required error',
      'PBG004 - Headline field shows a character counter',
      'PBG005 - Text fields enforce character limits',
      'PBG006 - Invalid slug values show a format validation error',
      'PBG007 - Cancelling reverts the title to its original value',
      'PBG008 - Saving changes persists all general fields',
      'PBG009 - Changes saved in Profile Builder are reflected in the End User page',
      'PBG010 - Share URL updates to reflect new slug after save without hard refresh',
      'PBG009M - Changes saved in Modern Profile Builder are reflected in the Modern End User page',
      'PBG010M - Modern Share URL updates to reflect new slug after save without hard refresh',
    ],
  },
  {
    id: 'CAT12', name: 'Profile Builder (Headshot)', tag: 'profile-builder-headshot',
    description: 'Headshot upload and management', active: true,
    scenarios: [
      'PBH001 - Gallery loads with Add New; Static and Animated type sheets both open',
      'PBH004 - Creating a static headshot shows it in the gallery',
      'PBH005 - Creating an animated headshot shows it in the gallery once generated',
      'PBH006 - Hovering a headshot card reveals the Set as my profile button',
      'PBH009 - Active headshot is reflected and cleared on the Classic EU page',
      'PBH009M - Active headshot is reflected and cleared on the Modern EU page',
      'PBH007 - Opening the Edit menu item opens the edit sheet',
      'PBH008 - Deleting a headshot removes it from the gallery',
    ],
  },
  {
    id: 'CAT13', name: 'Profile Builder (Social)', tag: 'profile-builder-social',
    description: 'Social links configuration', active: true,
    scenarios: [
      'PBS001 - Social Links section is visible with all network input fields',
      'PBS002 - Adding an Instagram URL shows its icon in the real-time preview',
      'PBS003 - All six social network icons appear in the preview after adding links',
      'PBS004 - Social link icons in the preview are anchor elements pointing to the correct domain',
      'PBS005 - Entering a handle for <network> normalises to the full URL after saving',
      'PBS006 - Cancelling reverts all social link changes',
    ],
  },
  {
    id: 'CAT14', name: 'Profile Builder (Visual)', tag: 'profile-builder-visual',
    description: 'Visual customization', active: true,
    scenarios: [
      'PBV001 - Color picker panel opens when clicking the color button',
      'PBV002 - Clicking a color preset immediately updates the preview',
      'PBV003 - Typing a hex value in the input immediately updates the preview',
      'PBV004 - Saving a color change reflects it in the end user page',
    ],
  },
  {
    id: 'CAT15', name: 'Sections (URL/Media)', tag: 'profile-builder-sections',
    description: 'URL and media sections', active: true,
    scenarios: [
      'PSN001 - Add Section opens the type selector; selecting URL and Media opens the two-tab editor',
      'PSN002 - URL validation, adding a link, and card content display',
      'PSN003 - Multiple URLs can be added in sequence to the same section',
      'PSN004 - URL cards can be reordered by drag-and-drop',
      'PSN005 - Edit Link updates the card on save and reverts it on cancel',
      'PSN006 - Edit Link allows replacing the card image',
      'PSN007 - Delete Link removes the URL card from the section editor',
      'PSN008 - Visual tab: default title placeholder, custom title, and card style updates',
      'PSN009 - Saving the section fires the API request and the section appears on the page',
      'PSN010 - Discard modal: Cancel and X open it; Go back returns to the editor; Discard closes it',
      'PSN011 - Visual tab offers Button, Card, and Stack display styles',
      'PSN012 - Selecting each card style updates the section preview',
    ],
  },
  {
    id: 'CAT16', name: 'Sections (Digital Product)', tag: 'sections-digital-product',
    description: 'Digital product sections', active: true,
    scenarios: [
      'DPS001 - Digital Product button opens a 3-tab editor with Thumbnail tab active',
      'DPS002 - Thumbnail required fields enable Next; currency is locked to USD; price format is validated',
      'DPS003 - Title enforces 50-character maximum and short description enforces 150-character maximum',
      'DPS004 - Selecting a thumbnail image opens the crop dialog and saves the selection',
      'DPS005 - Clicking the Landing Page tab directly bypasses required field validation',
      'DPS006 - Landing Page title enforces 300-character maximum and description has a formatting toolbar',
      'DPS007 - Slug field shows a live URL preview; CTA defaults to "Buy Now!" and enforces 30 characters',
      'DPS008 - Landing Page gallery supports up to 5 images and the Add button disables at the limit',
      'DPS009 - Upload file button opens the file browser',
      'DPS010 - External URL field validates format; Save button is disabled without all required fields',
      'DPS011 - File upload and External URL are mutually exclusive',
      'DPS012 - Clicking Next without required fields shows a validation error and stays on the Thumbnail tab',
      'DPS013 - Product preview updates in real time as the title is filled',
      'DPS014 - Cancel button and X button both open the discard confirmation modal',
      'DPS015 - Saving a fully configured Digital Product fires the save request and the section appears on the page',
    ],
  },
  {
    id: 'CAT17', name: 'EU Sections', tag: 'eu-sections',
    description: 'End-user sections display', active: true,
    scenarios: [
      'EUPSN001 - All URL Media styles (Button/Stack, Card/Square/Carousel, Card/Horizontal/Stack, Card/Horizontal/Carousel, Card/Vertical/Carousel) render correctly',
      'EUPSN002 - A section with many links shows all cards reachable and link opens correct URL',
      'EUDPS001 - Full purchase flow via URL delivery: card visible, landing page, Stripe checkout, post-purchase, and access',
      'EUDPS002 - Full purchase flow with file download delivery: card visible, landing page, Stripe checkout, and file download',
      'EUPSN001M - All URL Media styles render correctly on the Modern EU page',
      'EUPSN002M - A Modern EU section with many links shows all cards reachable and link opens correct URL',
      'EUDPS001M - Full purchase flow via URL delivery on the Modern EU page',
      'EUDPS002M - Full purchase flow with file download delivery on the Modern EU page',
    ],
  },
  {
    id: 'CAT18', name: 'Income', tag: 'income',
    description: 'Income tracking (WIP)', active: false,
    scenarios: [],
  },
  {
    id: 'CAT19', name: 'Audience', tag: 'audience',
    description: 'Audience management', active: true,
    scenarios: [
      'AUD001 - Audience page loads with all required UI elements',
      'AUD002 - Searching filters the list and clearing the tag with X restores the input',
      'AUD003 - Searching with no match shows the no results state',
      'AUD004 - Date picker Apply filters the list; Cancel discards the selection',
      'AUD005 - All column flags can be toggled on and off in the audience table',
      'AUD006 - Export CSV modal can be cancelled or confirmed to send',
      'AUD007 - Banning then unbanning a user cycles the status badge correctly',
      'AUD008 - A newly signed-up end-user appears in the Audience list',
      'AUD008M - A newly signed-up Modern EU user appears in the Audience list',
    ],
  },
  {
    id: 'CAT20', name: 'Settings Team', tag: 'settings-team',
    description: 'Team member settings', active: true,
    scenarios: [
      'STM001 - Settings Team Members page and invite modal load with required UI elements',
      'STM002 - Invite list supports adding and removing emails, and the modal can be cancelled',
      'STM003 - Inviting an existing myAvatar user sends an email and allows login to accept',
      'STM004 - Inviting a new user sends an email and allows signup to accept',
      'STM005 - A member\'s role can be toggled between Member and Admin',
      'STM006 - Deleting a member via the actions menu removes them from the list',
      'STM007 - Resending an invite sends a new email with a valid invite link',
      'STM008 - Copying an invite link gives a valid invite URL',
      'STM009 - Deleting an invite makes the link invalid',
    ],
  },
  {
    id: 'CAT21', name: 'Settings Membership', tag: 'settings-membership-payments',
    description: 'Membership and payments', active: true,
    scenarios: [
      'SMP001 - Pricing tab shows fixed USD price and Benefits tab lists subscriber perks',
      'SMP002 - Stripe card shows Connected status and Manage button when provider is already connected',
    ],
  },
  {
    id: 'CAT22', name: 'Settings Billing', tag: 'settings-billing',
    description: 'Billing configuration', active: true,
    scenarios: [
      'BIL001 - Plans & Usage tab displays current plan information',
      'BIL002 - Upgrade plan from Starter to Professional',
      'BIL003 - Downgrade plan from Professional to Starter schedules the change',
      'BIL004 - Cancel scheduled downgrade restores the active plan',
      'BIL005 - Cancel plan via 3-dot menu schedules plan cancellation',
      'BIL006 - Keep plan cancels the scheduled cancellation and restores the subscription',
      'BIL007 - Payment Method tab displays current credit card information',
      'BIL008 - Change Credit Card updates the payment method successfully',
    ],
  },
  {
    id: 'CAT23', name: 'Health Check', tag: 'health-check',
    description: 'System health validation', active: true,
    scenarios: [
      'HC001 - Health check panel opens automatically on the first dashboard visit and stays dismissed on revisit',
      'HC002 - Clicking a health check item expands it exclusively and collapses all others',
      'HC003 - Each health check action button navigates to the correct destination',
      'HC004 - Progress bar correctly tracks health check item completion and removal',
    ],
  },
]
