import type { CatInfo } from '@/types'

export const CATS: CatInfo[] = [
  {
    id: 'CAT03', name: 'Login', tag: 'login',
    description: 'User authentication flows', active: true,
    scenarios: [
      'Login with valid credentials',
      'Login with invalid credentials shows error',
      'Login with empty fields shows validation',
      'Logout successfully',
    ],
  },
  {
    id: 'CAT04', name: 'Avatar Management', tag: 'avatar-management',
    description: 'Create and manage avatars', active: true,
    scenarios: [
      'Create a new avatar',
      'Edit avatar name',
      'Delete an avatar',
      'Switch between avatars',
    ],
  },
  {
    id: 'CAT05', name: 'Home', tag: 'home',
    description: 'Home page features', active: true,
    scenarios: [
      'Home page loads for authenticated user',
      'Navigate to profile builder from home',
      'Navigate to knowledge base from home',
    ],
  },
  {
    id: 'CAT06', name: 'Knowledge Base', tag: 'knowledge-base',
    description: 'KB creation and management', active: true,
    scenarios: [
      'Create a knowledge base entry',
      'Edit a knowledge base entry',
      'Delete a knowledge base entry',
      'Search knowledge base',
    ],
  },
  {
    id: 'CAT07', name: 'EU Authentication', tag: 'end-user-auth',
    description: 'End-user auth flows', active: true,
    scenarios: [
      'End user can sign up with email',
      'End user can log in with email',
      'End user can log in with Google',
      'End user can log in with Facebook',
      'End user receives magic link email',
    ],
  },
  {
    id: 'CAT08', name: 'End User', tag: 'end-user',
    description: 'End-user experience', active: true,
    scenarios: [
      'End user sees avatar profile page',
      'End user can interact with avatar chat',
      'End user sees sections on profile',
      'End user can subscribe to membership',
    ],
  },
  {
    id: 'CAT09', name: 'Chat Log', tag: 'chat-log',
    description: 'Chat history and logs', active: true,
    scenarios: [
      'Chat log shows conversation history',
      'Chat log can be filtered by date',
      'Chat log shows user messages',
      'Chat log export works',
    ],
  },
  {
    id: 'CAT10', name: 'Video AI', tag: 'video-ai',
    description: 'Video AI generation', active: true,
    scenarios: [
      'VAI001 - Video AI page loads',
      'VAI002 - Upload image for Video AI',
      'VAI003 - Generate video from image',
      'VAI004 - Select creativity level',
      'VAI005 - Crop image before generation',
      'VAI006 - Download generated video',
      'VAI007 - Generated video appears in list',
      'VAI008 - Delete generated video',
      'VAI009 - Video AI with English UI',
      'VAI010 - Video thumbnail displays correctly',
      'VAI011 - Video AI works on modern EU',
      'VAI012 - Video AI generation completes',
    ],
  },
  {
    id: 'CAT11', name: 'Profile Builder (General)', tag: 'profile-builder-general',
    description: 'General profile settings', active: true,
    scenarios: [
      'Update display name',
      'Update bio',
      'Update location',
      'Update website URL',
      'Changes are saved successfully',
    ],
  },
  {
    id: 'CAT12', name: 'Profile Builder (Headshot)', tag: 'profile-builder-headshot',
    description: 'Headshot upload and management', active: true,
    scenarios: [
      'Upload headshot image',
      'Crop headshot image',
      'Remove headshot image',
      'Headshot displays on profile',
    ],
  },
  {
    id: 'CAT13', name: 'Profile Builder (Social)', tag: 'profile-builder-social',
    description: 'Social links configuration', active: true,
    scenarios: [
      'Add Instagram link',
      'Add Twitter/X link',
      'Add LinkedIn link',
      'Add YouTube link',
      'Remove social link',
      'Social links display on EU profile',
    ],
  },
  {
    id: 'CAT14', name: 'Profile Builder (Visual)', tag: 'profile-builder-visual',
    description: 'Visual customization', active: true,
    scenarios: [
      'Change profile background color',
      'Change profile theme',
      'Upload background image',
      'Preview changes in real time',
    ],
  },
  {
    id: 'CAT15', name: 'Sections (URL/Media)', tag: 'profile-builder-sections',
    description: 'URL and media sections', active: true,
    scenarios: [
      'Add URL section',
      'Add media section',
      'Edit section title',
      'Reorder sections',
      'Delete section',
      'Section displays on EU profile',
    ],
  },
  {
    id: 'CAT16', name: 'Sections (Digital Product)', tag: 'sections-digital-product',
    description: 'Digital product sections', active: true,
    scenarios: [
      'Add digital product section',
      'Set product price',
      'Upload product image',
      'Digital product displays on EU page',
      'End user can purchase digital product',
      'Free digital product download works',
    ],
  },
  {
    id: 'CAT17', name: 'EU Sections', tag: 'eu-sections',
    description: 'End-user sections display', active: true,
    scenarios: [
      'EU page shows all active sections',
      'EU page URL section renders correctly',
      'EU page media section renders correctly',
      'EU page digital product section renders correctly',
      'EU Modern style renders sections correctly',
    ],
  },
  {
    id: 'CAT19', name: 'Audience', tag: 'audience',
    description: 'Audience management', active: true,
    scenarios: [
      'Audience list loads',
      'Filter audience by subscription status',
      'Export audience list',
      'View subscriber details',
    ],
  },
  {
    id: 'CAT20', name: 'Settings Team', tag: 'settings-team',
    description: 'Team member settings', active: true,
    scenarios: [
      'Invite team member by email',
      'Invited member appears in pending list',
      'Revoke team member invitation',
      'Change team member role',
      'Remove team member',
    ],
  },
  {
    id: 'CAT21', name: 'Settings Membership', tag: 'settings-membership-payments',
    description: 'Membership and payments', active: true,
    scenarios: [
      'Create membership tier',
      'Edit membership tier price',
      'Delete membership tier',
      'Membership tier displays on EU page',
      'End user can subscribe to membership',
      'End user can cancel membership',
    ],
  },
  {
    id: 'CAT22', name: 'Settings Billing', tag: 'settings-billing',
    description: 'Billing configuration', active: true,
    scenarios: [
      'Billing page loads',
      'Current plan is displayed',
      'Upgrade plan flow works',
      'Payment method can be updated',
      'Invoice history is visible',
    ],
  },
  {
    id: 'CAT23', name: 'Health Check', tag: 'health-check',
    description: 'System health validation', active: true,
    scenarios: [
      'Health check panel loads',
      'Incomplete items shown as uncompleted',
      'First uncompleted item is expanded by default',
      'Completing a step marks it as done',
      'All steps completed shows success state',
    ],
  },
  {
    id: 'CAT01', name: 'Signup', tag: 'signup',
    description: 'New user registration (WIP)', active: false,
    scenarios: [],
  },
  {
    id: 'CAT02', name: 'Onboarding', tag: 'onboarding',
    description: 'User onboarding flow (WIP)', active: false,
    scenarios: [],
  },
  {
    id: 'CAT18', name: 'Income', tag: 'income',
    description: 'Income tracking (WIP)', active: false,
    scenarios: [],
  },
]
